FROM gliderlabs/alpine:3.2
MAINTAINER Greg Poirier <greg@opsee.co>

ENV GOROOT /usr/lib/go
ENV GOPATH /gopath
ENV GOBIN /gopath/bin
ENV PATH $PATH:$GOROOT/bin:$GOPATH/bin

RUN apk update && \
    apk add curl git mercurial bzr go bash && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /export && \
    mkdir -p /gopath/bin && \
    mkdir -p /build && \
    go get github.com/constabulary/gb/...

COPY . /build

RUN ln -sf /build/scripts/build.sh /build.sh

CMD ["/build.sh"]
